[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  base = "."

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"
  autoLaunch = true

[context.production.environment]
  VITE_APP_ENV = "production" 